### ISSUE TITLE
Problem with tmap index

### ISSUE THREAD

**Issue by fplazaonate** [iontorrent/TMAP#10]
Hi, 
I  tried to index a 3 million entries FASTA file.
I stopped TMAP index after 18 hours of computing because I thought it was abnormally long. (correct me if I am wrong)
By invoking gstack, TMAP seemed to be stuck in the tmap_refseq_fasta2pac function

```
#0  0x00007f5194e06e0e in __strcmp_sse42 () from /lib64/libc.so.6
#1  0x0000000000429ba9 in tmap_refseq_fasta2pac (fn_fasta=0x18d3610 "bgi_june2009_genes.tfa", compression=compression@entry=0, fwd_only=fwd_only@entry=0) at src/index/tmap_refseq.c:342
#2  0x000000000042786d in tmap_index_core (opt=0x7fff44f2c5c0) at src/index/tmap_index.c:76
#3  tmap_index (argc=3, argv=0x7fff44f2c710) at src/index/tmap_index.c:190
#4  0x0000000000403b3f in main (argc=4, argv=0x7fff44f2c708) at src/tmap_main.c:201
```

Do you know how to solve this problem?
Thanks in advance.

**Comment by ghost** [comment]
Hi, please repost this question on http://ioncommunity.lifetechnologies.com/    It will get more visibility there with the product support and software dev teams.

Also note that this TMAP repo is no longer maintained or developed.    The current versions of TMAP that are released with Torrent Suite are here https://github.com/iontorrent/TS/tree/master/Analysis/TMAP   Try the latest code there to see if you can reproduce the problem.

I know there is an upper limit to genome size.   hg19 certainly works, but the very largest genomes will fail.

**Comment by fplazaonate** [comment]
Thanks for your answer.
I will try with the new repo.
